---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-1.9
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:1.9 -f Dockerfile-1.9 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:1.9
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:1.9 nephatrine/gitea-web:1.9
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.9
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:1.9
- name: build-1.10
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:1.10 -f Dockerfile-1.10 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:1.10
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:1.10 nephatrine/gitea-web:1.10
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.10
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:1.10
- name: build-1.11
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:1.11 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:1.11
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:1.11 nephatrine/gitea-web:1.11
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.11
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:1.11
- name: build-latest
  commands:
  - docker tag nephatrine/gitea-web:1.11 pdr.nephatrine.net/nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:latest
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:latest nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:latest
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:latest
  depends_on:
  - build-1.11

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: webhook-id
    webhook_token:
      from_secret: webhook-token

depends_on:
- default