---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-previous
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:previous -f Dockerfile-old .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:previous
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:previous nephatrine/gitea-web:1.11
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.11
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:previous nephatrine/gitea-web:previous
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:previous
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:previous
- name: build-latest
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:latest
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:latest nephatrine/gitea-web:1.12
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.12
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:latest nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:latest
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: bfb044536151c79e455dde13651fe8b5e822f3930e7e79374a14bfef6dee96ee

...
