---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/gitea-web:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:latest
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:latest nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:latest
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: c031faa50a0d38fd568ce2ed6a56c350eba57a40e9574a6b0738fc7029402f36

...
