---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-1.14
  commands:
  - docker build -t nephatrine/gitea-web:1.14 .
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.14
- name: build-latest
  commands:
  - docker tag nephatrine/gitea-web:1.14 pdr.nephatrine.net/nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:latest
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:latest nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:latest
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:latest
  depends_on:
  - build-1.14

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 28c3b4257ae5139cd17ae0ac719dd7ce50ac8cc59805903728dd6462ffba6d36

...
