---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-1.11
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:1.11 -f Dockerfile-1.11 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:1.11
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:1.11 nephatrine/gitea-web:1.11
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.11
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:1.11
- name: build-1.12
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:1.12 -f Dockerfile-1.12 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:1.12
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:1.12 nephatrine/gitea-web:1.12
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.12
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:1.12
- name: build-1.13
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/gitea-web:1.13 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:1.13
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:1.13 nephatrine/gitea-web:1.13
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:1.13
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:1.13
- name: build-latest
  commands:
  - docker tag nephatrine/gitea-web:1.13 pdr.nephatrine.net/nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/gitea-web:latest
  - docker tag pdr.nephatrine.net/nephatrine/gitea-web:latest nephatrine/gitea-web:latest
  - HOME=/mnt/config/home docker push nephatrine/gitea-web:latest
  - docker rmi pdr.nephatrine.net/nephatrine/gitea-web:latest
  depends_on:
  - build-1.13

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: b25f9a962ccb89070068f73ae55280759708fa5036e97afb140894413d5fd024

...
