# SPDX-FileCopyrightText: 2019-2025 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: CC0-1.0

services:
  gitea-web:
    build: .
    container_name: gitea-web
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
    ports:
      - "3000:3000/tcp"
      - "22:2020/tcp"
    volumes:
      - /mnt/containers/gitea-web:/mnt/config
