#!/usr/bin/with-contenv bash

if [[ ! -d /mnt/config/etc/gitea ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/gitea
fi
s6-setuidgid guardian cp -n /etc/gitea/* /mnt/config/etc/gitea/
s6-setuidgid guardian cp /etc/gitea/app.ini.sample /mnt/config/etc/gitea/app.ini.sample

if [[ -d /mnt/config/data/git ]]; then
  find /mnt/config/data/git/ -name hooks -type d | xargs -n1 -I[] find [] -type f -exec chmod 0755 {} \;
fi