#!/usr/bin/with-contenv bash

B_DSA=${B_DSA:-1024}
B_RSA=${B_RSA:-4096}
B_ECDSA=${B_ECDSA:-384}

if [[ ! -d /mnt/config/etc/ssh ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/ssh
fi
if [[ ! -e /mnt/config/etc/ssh/sshd_config ]]; then
  s6-setuidgid guardian cp /etc/ssh/sshd_config /mnt/config/etc/ssh/sshd_config
fi

if egrep -v '^#' /mnt/config/etc/ssh/sshd_config | grep -q '/etc/ssh/ssh_host_key'; then
  if [[ ! -e /mnt/config/etc/ssh/ssh_host_key && -e /mnt/config/etc/ssh/ssh_host_key.pub ]]; then
    ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N ''
    cp /etc/ssh/ssh_host_key* /mnt/config/etc/ssh/
    chown guardian:users /mnt/config/etc/ssh/ssh_host_key*
  fi
  if [[ -e /mnt/config/etc/ssh/ssh_host_key ]]; then
    cp /mnt/config/etc/ssh/ssh_host_key* /etc/ssh/
    chmod 600 /etc/ssh/ssh_host_key
    chmod 644 /etc/ssh/ssh_host_key.pub
  fi
fi

if egrep -v '^#' /mnt/config/etc/ssh/sshd_config | grep -q '/etc/ssh/ssh_host_dsa_key'; then
  if [[ ! -e /mnt/config/etc/ssh/ssh_host_dsa_key && -e /mnt/config/etc/ssh/ssh_host_dsa_key.pub ]]; then
    ssh-keygen -t dsa -b ${B_DSA} -f /etc/ssh/ssh_host_dsa_key -N ''
    cp /etc/ssh/ssh_host_dsa_key* /mnt/config/etc/ssh/
    chown guardian:users /mnt/config/etc/ssh/ssh_host_dsa_key*
  fi
  if [[ -e /mnt/config/etc/ssh/ssh_host_dsa_key ]]; then
    cp /mnt/config/etc/ssh/ssh_host_dsa_key* /etc/ssh/
    chmod 600 /etc/ssh/ssh_host_dsa_key
    chmod 644 /etc/ssh/ssh_host_dsa_key.pub
  fi
fi

if egrep -v '^#' /mnt/config/etc/ssh/sshd_config | grep -q '/etc/ssh/ssh_host_rsa_key'; then
  if [[ ! -e /mnt/config/etc/ssh/ssh_host_rsa_key && -e /mnt/config/etc/ssh/ssh_host_rsa_key.pub ]]; then
    ssh-keygen -t rsa -b ${B_RSA} -f /etc/ssh/ssh_host_rsa_key -N ''
    cp /etc/ssh/ssh_host_rsa_key* /mnt/config/etc/ssh/
    chown guardian:users /mnt/config/etc/ssh/ssh_host_rsa_key*
  fi
  if [[ -e /mnt/config/etc/ssh/ssh_host_rsa_key ]]; then
    cp /mnt/config/etc/ssh/ssh_host_rsa_key* /etc/ssh/
    chmod 600 /etc/ssh/ssh_host_rsa_key
    chmod 644 /etc/ssh/ssh_host_rsa_key.pub
  fi
fi

if egrep -v '^#' /mnt/config/etc/ssh/sshd_config | grep -q '/etc/ssh/ssh_host_ecdsa_key'; then
  if [[ ! -e /mnt/config/etc/ssh/ssh_host_ecdsa_key && -e /mnt/config/etc/ssh/ssh_host_ecdsa_key.pub ]]; then
    ssh-keygen -t ecdsa -b ${B_ECDSA} -f /etc/ssh/ssh_host_ecdsa_key -N ''
    cp /etc/ssh/ssh_host_ecdsa_key* /mnt/config/etc/ssh/
    chown guardian:users /mnt/config/etc/ssh/ssh_host_ecdsa_key*
  fi
  if [[ -e /mnt/config/etc/ssh/ssh_host_ecdsa_key ]]; then
    cp /mnt/config/etc/ssh/ssh_host_ecdsa_key* /etc/ssh/
    chmod 600 /etc/ssh/ssh_host_ecdsa_key
    chmod 644 /etc/ssh/ssh_host_ecdsa_key.pub
  fi
fi

if egrep -v '^#' /mnt/config/etc/ssh/sshd_config | grep -q '/etc/ssh/ssh_host_ed25519_key'; then
  if [[ ! -e /mnt/config/etc/ssh/ssh_host_ed25519_key && -e /mnt/config/etc/ssh/ssh_host_ed25519_key.pub ]]; then
    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
    cp /etc/ssh/ssh_host_ed25519_key* /mnt/config/etc/ssh/
    chown guardian:users /mnt/config/etc/ssh/ssh_host_ed25519_key*
  fi
  if [[ -e /mnt/config/etc/ssh/ssh_host_ed25519_key ]]; then
    cp /mnt/config/etc/ssh/ssh_host_ed25519_key* /etc/ssh/
    chmod 600 /etc/ssh/ssh_host_ed25519_key
    chmod 644 /etc/ssh/ssh_host_ed25519_key.pub
  fi
fi
