#!/usr/bin/with-contenv bash

B_MODULI=${B_MODULI:-4096}

s6-setuidgid guardian touch /mnt/config/log/sshd.log

if ! pgrep sshd >/dev/null; then
  if [[ ! -e /mnt/config/etc/ssh/moduli ]]; then
    ssh-keygen -M generate -O bits=${B_MODULI} /etc/ssh/moduli.candidates && ssh-keygen -M screen -f /etc/ssh/moduli.candidates /etc/ssh/moduli.safe && mv /etc/ssh/moduli.safe /etc/ssh/moduli
    s6-setuidgid guardian cp /etc/ssh/moduli /mnt/config/etc/ssh/moduli
    rm -f /etc/ssh/moduli.candidates
  fi
  cp /mnt/config/etc/ssh/moduli /etc/ssh/moduli
  chmod 644 /etc/ssh/moduli

  exec /usr/sbin/sshd -E /mnt/config/log/sshd.log -f /mnt/config/etc/ssh/sshd_config;
  sleep 5
fi

while pgrep sshd >/dev/null; do
  sleep 30
done