#!/bin/sh

export HOME=/mnt/config/home

cd /mnt/config/home || exit 1

# Copy Config

if [ ! -d /mnt/config/etc ]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/etc
fi
if [ -d /mnt/config/etc ]; then
  if [ ! -f /mnt/config/etc/gitea.ini ]; then
    /command/s6-setuidgid guardian /bin/cp /etc/gitea.ini /mnt/config/etc/gitea.ini
  fi
  /command/s6-setuidgid guardian /bin/cp /etc/gitea.ini.sample /mnt/config/etc/gitea.ini.sample
fi

# Ensure Git Hooks Executable

if [ -d /mnt/config/data/git ]; then
  /usr/bin/find /mnt/config/data/git/ -name hooks -type d | /usr/bin/xargs -n1 -I[] /usr/bin/find [] -type f -exec /bin/chmod 0700 {} \;
fi

# Start Service

GITEA_CUSTOM=/mnt/config/www/gitea USER=guardian exec /command/s6-setuidgid guardian /usr/bin/gitea web --config /mnt/config/etc/gitea.ini --pid /tmp/gitea.pid;
