#!/bin/bash

# Build Config

if [[ ! -d /mnt/config/etc ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/etc
fi
if [[ -f /mnt/config/etc/gitea/app.ini && ! -f /mnt/config/etc/gitea.ini ]]; then
  /command/s6-setuidgid guardian /bin/mv /mnt/config/etc/gitea/app.ini /mnt/config/etc/gitea.ini
  if [[ -f /mnt/config/home/.ssh/authorized_keys ]]; then
    /command/s6-setuidgid guardian /bin/sed -i 's~/mnt/config/etc/gitea/app.ini~/mnt/config/etc/gitea.ini~g' /mnt/config/home/.ssh/authorized_keys
  fi
  if [[ -d /mnt/config/data/git/repos ]]; then
    /usr/bin/find /mnt/config/data/git/repos -name hooks -type d | xargs -n1 -I[] /command/s6-setuidgid guardian /bin/sed -i 's~/mnt/config/etc/gitea/app.ini~/mnt/config/etc/gitea.ini~g' []/pre-receive.d/gitea []/post-receive.d/gitea []/update.d/gitea
  fi
fi
if [[ ! -f /mnt/config/etc/gitea.ini ]]; then
  /command/s6-setuidgid guardian /bin/cp /etc/gitea.ini /mnt/config/etc/gitea.ini
fi
/command/s6-setuidgid guardian /bin/cp /etc/gitea.ini.sample /mnt/config/etc/gitea.ini.sample

# Ensure Git Hooks Executable

if [[ -d /mnt/config/data/git ]]; then
  /usr/bin/find /mnt/config/data/git/ -name hooks -type d | /usr/bin/xargs -n1 -I[] /usr/bin/find [] -type f -exec /bin/chmod 0700 {} \;
fi

# Start Service

export HOME=/mnt/config/home
GITEA_CUSTOM=/mnt/config/www/gitea USER=guardian exec /command/s6-setuidgid guardian /usr/bin/gitea web --config /mnt/config/etc/gitea.ini --pid /tmp/gitea.pid;
